version: 2

sources:
  - name: clean_grp3
    tables:
      - name: clean_lto_motor_vehicles
      - name: clean_dpwh_avg_iri
      - name: clean_dpwh_road_density
      - name: clean_dpwh_bridge_condition
  - name: mart_grp3
    tables:
      - name: dim_region
