name: "capstone_infra"
version: "1.0"
config-version: 2

profile: clickhouse_ftw
model-paths: ["models"]
macro-paths: ["macros"]  

models:
  capstone_infra:
    clean:
      +schema: clean_grp3
      +materialized: table
    mart:
      +schema: mart_grp3
      +materialized: view