clickhouse_ftw: 
  target: remote
  outputs:
      remote:
        type: clickhouse
        host: 54.87.106.52 # For REMOTE class: set to your server IP/DNS, e.g. 34.12.34.56
        port: 8123
        user: ftw_grp3            # same creds you already use
        password: Squirtle#007_FTW
        schema: mart_grp3
        threads: 4
        secure: false